### ISSUE TITLE
The profile.html template has a misplaced loop that creates invalid html

### ISSUE THREAD

**Issue by rofrano** [cloudyuga/rsvpapp#12]
In `./templates/profile.html`, the loop that iterates over the items in the table is off by one line creating invalid html. `<tbody><tr>` is inside the loop while `</tr></tbody>` is outside the loop. I don't believe you meant to define a new table body for every row and not terminate any but the last so you want `tr` inside the loop and `tbody` outside of it. 

**Current code:**

```html
  {% for item in items %}
  <tbody>
    <tr class="danger">
      <td class="text-center">{{ item.name }} </td>
      <td class="text-center">{{ item.email }}</td>
    {% endfor %}
      </tr>
    </tbody>
```

**Corrected code:**

```html
  <tbody>
    {% for item in items %}
    <tr class="danger">
      <td class="text-center">{{ item.name }} </td>
      <td class="text-center">{{ item.email }}</td>
    </tr>
    {% endfor %}
  </tbody>
```
I can fork the repo and submit a pull request if you don't have time to fix it.

**Comment by cloudyuga** [comment]
Thanks @rofrano. I have fixed it here.
